// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "TrainWWDC",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "TrainWWDC",
            targets: ["AppModule"],
            bundleIdentifier: "com.gabrielrossi.TrainWWDC",
            teamIdentifier: "HT9NV9BAKV",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .phone,
                .pad
            ],
            supportedInterfaceOrientations: [
                .portrait
            ],
            appCategory: .arcadeGames
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
